const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = { window: {} };
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname, '../timing.js'), 'utf8'), context);
const Timing = context.window.LPRLapTiming;
const timing = new Timing([10000, 12000, 18000]);
assert.equal(timing.split(9000).delta, -1000);
const second = timing.split(22000);
assert.equal(second.time, 13000);
assert.equal(second.delta, 1000);
const last = timing.split(40000);
assert.equal(last.sector, 3);
assert.equal(last.time, 18000);
assert.equal(last.delta, 0);
assert.equal(timing.split(41000), null);
timing.reset();
assert.equal(timing.split(0), null);
assert.equal(timing.split(10000).sector, 1);
assert.equal(timing.split(9999), null);
assert.equal(new Timing().split(10000).delta, null);
assert.equal(new Timing([1, -2, 3]).best, null);
console.log('PASS: sector durations, personal-best comparisons, reset and invalid timestamps');
